### ISSUE TITLE
Some colors are not displayed when printing report

### ISSUE THREAD

**Issue by robinarmingaud** [CERN/CAiMIRA#5]
![image](https://user-images.githubusercontent.com/92796643/171658637-8ef08904-984c-4861-a999-746c48026404.png)
Hi, i'll try to post here issues we encountered with CARA. For this issue it is just necessary to add :

body {
        -webkit-print-color-adjust: exact; /*chrome & webkit browsers*/
        color-adjust: exact; /*firefox & IE */
}

in report.css

**Comment by lrdossan** [comment]
Solved with this commit - https://gitlab.cern.ch/caimira/caimira/-/commit/d0b5e9b2a7396e49a31331e3cd140821acfc5cb3
