### ISSUE TITLE
Base scenario is calculated twice causing small differencies

### ISSUE THREAD

**Issue by robinarmingaud** [CERN/CAiMIRA#6]
![image](https://user-images.githubusercontent.com/92796643/171806027-dc92f960-ea50-45ad-8bd9-a876f33abad2.png)
![image](https://user-images.githubusercontent.com/92796643/171806113-1f5ff307-9646-4398-b6d0-a266f6fa488b.png)

**Comment by lrdossan** [comment]
Solved with https://gitlab.cern.ch/caimira/caimira/-/merge_requests/367
